name: check css format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: install node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: install prettier
      run: npm i prettier -g
    - name: check format using prettier
      run: prettier --check '*.css'
